In [1]:
import pandas as pd

In [2]:
bond = pd.read_csv("jamesbond.csv")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [4]:
bond = pd.read_csv("jamesbond.csv", index_col="Film")
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [17]:
bond = pd.read_csv("jamesbond.csv")
bond = bond.set_index("Film")
bond.head()
# bond.reset_index()
# bond.reset_index(drop=True)
bond = bond.reset_index().set_index("Year")
bond.head()

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN

In [8]:
bond = pd.read_csv("jamesbond.csv")
bond.head()

bond.iloc[5]
bond.iloc[[15, 20]]
bond.iloc[4:8]
bond.iloc[:6]
bond.iloc[20:]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [23]:
bond = pd.read_csv("jamesbond.csv", index_col="Film")
bond.head()

bond.loc["Goldfinger"]
bond.loc["GoldenEye"]
bond.loc["Casino Royale"]
# bond.loc["Sacred Bond"]
bond.loc[["Octopussy", "Moonraker"]]
bond.loc[["Octopussy", "Moonraker", "Casino Royale"]]
# bond.loc[["Octopussy", "Moonraker", "Casino Royale", "Gold Bond"]]
bond.loc["Diamonds Are Forever":"Moonraker"]
bond.loc["GoldenEye":]
bond.loc[:"On Her Majesty's Secret Service"]
bond.loc["Casino Royale"]
# bond.loc[:"Casino Royale"]  # non-unique

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3

In [17]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

bond.loc["Diamonds Are Forever", "Director"]
bond.loc[["Octopussy", "GoldenEye"], "Director"]
bond.loc[["Octopussy", "GoldenEye"], "Director":"Budget"]
bond.loc["GoldenEye":"Octopussy", "Director":"Budget"]
bond.loc["GoldenEye":"Octopussy", ["Actor", "Bond Actor Salary", "Year"]]

bond.iloc[0, 2]
bond.iloc[3, 5]
bond.iloc[[0, 2], 3]
bond.iloc[[0, 2], [3, 5]]
bond.iloc[:7, :3]

                      Year           Actor         Director
Film
A View to a Kill      1985     Roger Moore        John Glen
Casino Royale         2006    Daniel Craig  Martin Campbell
Casino Royale         1967     David Niven       Ken Hughes
Diamonds Are Forever  1971    Sean Connery     Guy Hamilton
Die Another Day       2002  Pierce Brosnan     Lee Tamahori
Dr. No                1962    Sean Connery    Terence Young
For Your Eyes Only    1981     Roger Moore        John Glen

In [13]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

# bond["Actor"].loc["Diamonds Are Forever"] = "Sir Sean Connery"
bond.loc["Diamonds Are Forever", "Actor"] = "Sir Sean Connery"
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [20]:
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

# bond[bond["Actor"] == "Sean Connery"]
# bond["Actor"] = bond["Actor"].replace("Sean Connery", "Sir Sean Connery")
# bond

is_sean_connery = bond["Actor"] == "Sean Connery"
bond.loc[is_sean_connery, "Actor"] = "Sir Sean Connery"
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4