# DataFrame I

In [1]:
import pandas as pd

In [26]:
nba = pd.read_csv("nba.csv")
nba.head(n=2)
nba.tail(n=2)
nba.index
nba.values  # np.ndarray
nba.shape
nba.dtypes  # pd.Series
nba.columns
nba.axes
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    object
 3   Height    585 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    488 non-null    float64
dtypes: float64(2), object(5)
memory usage: 32.5+ KB

In [18]:
revenue = pd.read_csv("revenue.csv", index_col="Date")
revenue.sum(axis="index")
revenue.sum(axis="columns")
revenue.sum().sum()

np.int64(16250)

In [24]:
nba = pd.read_csv("nba.csv")
nba.Team  # Case sensitive
nba.Salary
nba.Name
# nba.name
type(nba.Name)
nba["Team"]
nba["Salary"]

# names = nba["Name"]
# names.iloc[0] = "Whatever"
# names.head()
# nba.head()

names = nba["Name"].copy()
names.iloc[0] = "Whatever"
names.head()
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [8]:
nba = pd.read_csv("nba.csv")
nba[["Name", "Team"]]
nba[["Team", "Name"]]
nba[["Salary", "Name", "Team"]]
columns_to_select = ["Position", "Name", "Team"]
nba[columns_to_select]

    Position               Name                Team
0          F         Saddiq Bey       Atlanta Hawks
1          G  Bogdan Bogdanovic       Atlanta Hawks
2          G        Kobe Bufkin       Atlanta Hawks
3          C       Clint Capela       Atlanta Hawks
4        F-C     Bruno Fernando       Atlanta Hawks
..       ...                ...                 ...
587        G       Ryan Rollins  Washington Wizards
588        G      Landry Shamet  Washington Wizards
589        F   Tristan Vukcevic  Washington Wizards
590        G       Delon Wright  Washington Wizards
591      NaN                NaN                 NaN

[592 rows x 3 columns]

In [18]:
nba = pd.read_csv("nba.csv")
# nba["Sport"] = "Basketball"
nba.insert(loc=3, column="Sport", value="Basketball")
nba["Salary Doubled"] = nba["Salary"].mul(2)
nba["New Salary"] = nba["Salary"].sub(5000000)

nba

,Name,Team,Position,Sport,Height,Weight,College,Salary,Salary Doubled,New Salary
0,Saddiq Bey,Atlanta Hawks,F,Basketball,6-7,215.0,Villanova,4556983.0,9113966.0,-443017.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,Basketball,6-5,225.0,Fenerbahce,18700000.0,37400000.0,13700000.0
2,Kobe Bufkin,Atlanta Hawks,G,Basketball,6-5,195.0,Michigan,4094244.0,8188488.0,-905756.0
3,Clint Capela,Atlanta Hawks,C,Basketball,6-10,256.0,Elan Chalon,20616000.0,41232000.0,15616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,Basketball,6-10,240.0,Maryland,2581522.0,5163044.0,-2418478.0
...,...,...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,Basketball,6-3,180.0,Toledo,1719864.0,3439728.0,-3280136.0
588,Landry Shamet,Washington Wizards,G,Basketball,6-4,190.0,Wichita State,10250000.0,20500000.0,5250000.0
589,Tristan Vukcevic,Washington Wizards,F,Basketball,6-10,220.0,Real Madrid,NaN,NaN,NaN
590,Delon Wright,Washington Wizards,G,Basketball,6-5,185.0,Utah,8195122.0,16390244.0,3195122.0
591,NaN,NaN,NaN,Basketball,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
nba = pd.read_csv("nba.csv")
nba["Team"].value_counts(dropna=False)
nba["Position"].value_counts(normalize=True) * 100
nba["Salary"].value_counts()

Salary
559782.0      59
1119563.0     27
3196448.0     13
2019706.0      9
1719864.0      8
              ..
2966040.0      1
10900635.0     1
4570080.0      1
7921300.0      1
8195122.0      1
Name: count, Length: 298, dtype: int64

In [15]:
nba = pd.read_csv("nba.csv")
nba.dropna()
nba.dropna(how="all")
nba.dropna(subset=["College"])
nba.dropna(subset=["College", "Salary"])

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
585,Eugene Omoruyi,Washington Wizards,F,6-6,235.0,Oregon,559782.0
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [12]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba.fillna(0)
nba["Salary"] = nba["Salary"].fillna(0)
nba["College"] = nba["College"].fillna(value="Unknown")
nba["College"].isna().sum()

np.int64(0)

In [24]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba["Salary"] = nba["Salary"].fillna(0)
nba.dtypes
nba["Salary"] = nba["Salary"].astype(int)
nba
nba["Weight"] = nba["Weight"].fillna(0).astype(int)
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215,Villanova,4556983
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225,Fenerbahce,18700000
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195,Michigan,4094244
3,Clint Capela,Atlanta Hawks,C,6-10,256,Elan Chalon,20616000
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240,Maryland,2581522
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194,Michigan,27955357
587,Ryan Rollins,Washington Wizards,G,6-3,180,Toledo,1719864
588,Landry Shamet,Washington Wizards,G,6-4,190,Wichita State,10250000
589,Tristan Vukcevic,Washington Wizards,F,6-10,220,Real Madrid,0
590,Delon Wright,Washington Wizards,G,6-5,185,Utah,8195122

In [10]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba.nunique()
print(nba.info())
nba["Position"] = nba["Position"].astype("category")
print(nba.info())
nba["Team"] = nba["Team"].astype("category")
print(nba.info())

<class 'pandas.core.frame.DataFrame'>
Index: 591 entries, 0 to 590
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    object
 3   Height    585 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    488 non-null    float64
dtypes: float64(2), object(5)
memory usage: 36.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 591 entries, 0 to 590
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    category
 3   Height    585 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    488 non-null    float64
dtypes: category(1), float64(2), object(4)
memory usage: 33.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 591 entries, 0 to 590
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    category
 2   Position  584 non-null    category
 3   Height    585 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    488 non-null    float64
dtypes: category(2), float64(2), object(3)
memory usage: 30.5+ KB
None

In [16]:
nba = pd.read_csv("nba.csv")
nba.sort_values("Name")
nba.sort_values(by="Name")
nba.sort_values("Name", ascending=False)
nba.sort_values("Salary", na_position="first", ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
23,Blake Griffin,Boston Celtics,F,6-9,250.0,Oklahoma,NaN
26,Mfiondu Kabengele,Boston Celtics,C,6-10,250.0,Florida State,NaN
28,Svi Mykhailiuk,Boston Celtics,G-F,6-7,205.0,Kansas,NaN
35,Robert Williams III,Boston Celtics,C-F,6-9,237.0,Texas A&M,NaN
39,Nic Claxton,Brooklyn Nets,C,6-11,215.0,Georgia,NaN
...,...,...,...,...,...,...,...
55,Leaky Black,Charlotte Hornets,F,6-9,209.0,North Carolina,559782.0
74,Onuralp Bitim,Chicago Bulls,F,6-6,215.0,NaN,559782.0
523,Sir'Jabari Rice,San Antonio Spurs,G,6-4,180.0,Texas,559782.0
540,Markquis Nowell,Toronto Raptors,G,5-8,160.0,Kansas State,559782.0
5,Trent Forrest,Atlanta Hawks,G,6-4,210.0,Florida State,508891.0

In [13]:
nba = pd.read_csv("nba.csv")
nba.sort_values(by=["Team", "Name"], ascending=[True, False])
nba.sort_values(by=["Position", "Salary"])
nba.sort_values(by=["Position", "Salary"], ascending=False)
nba = nba.sort_values(by=["Position", "Salary"], ascending=[True, False])
nba

,Name,Team,Position,Height,Weight,College,Salary
145,Nikola Jokic,Denver Nuggets,C,6-11,284.0,Mega Basket,47607350.0
344,Rudy Gobert,Minnesota Timberwolves,C,7-1,258.0,Cholet,41000000.0
453,Deandre Ayton,Phoenix Suns,C,7-0,250.0,Arizona,32459438.0
329,Brook Lopez,Milwaukee Bucks,C,7-1,282.0,Stanford,25000000.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
...,...,...,...,...,...,...,...
299,Caleb Daniels,Miami Heat,NaN,NaN,NaN,NaN,1119563.0
541,Kevin Obanor,Toronto Raptors,NaN,6-8,235.0,NaN,1119563.0
564,Nick Ongenda,Utah Jazz,NaN,NaN,NaN,NaN,1119563.0
15,Miles Norris,Atlanta Hawks,NaN,NaN,NaN,NaN,559782.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
nba = pd.read_csv("nba.csv")
nba = nba.sort_values(["Team", "Name"])
nba.sort_index()
nba = nba.sort_index(ascending=False)
nba

,Name,Team,Position,Height,Weight,College,Salary
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
...,...,...,...,...,...,...,...
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0

In [25]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba["Salary"] = nba["Salary"].fillna(0).astype(int)
nba["Salary Rank"] = nba["Salary"].rank(ascending=False).astype(int)
nba.sort_values("Salary", ascending=False).head(10)

,Name,Team,Position,Height,Weight,College,Salary,Salary Rank
175,Stephen Curry,Golden State Warriors,G,6-2,185.0,Davidson,51915615,1
461,Kevin Durant,Phoenix Suns,F,6-10,240.0,Texas,47649433,2
145,Nikola Jokic,Denver Nuggets,C,6-11,284.0,Mega Basket,47607350,4
436,Joel Embiid,Philadelphia 76ers,C-F,7-0,280.0,Kansas,47607350,4
261,LeBron James,Los Angeles Lakers,F,6-9,250.0,St. Vincent-St. Mary HS (OH),47607350,4
456,Bradley Beal,Phoenix Suns,G,6-4,207.0,Florida,46741590,6
480,Damian Lillard,Portland Trail Blazers,G,6-2,195.0,Weber State,45640084,8
316,Giannis Antetokounmpo,Milwaukee Bucks,F,7-0,243.0,Filathlitikos,45640084,8
239,Paul George,Los Angeles Clippers,F,6-8,220.0,Fresno State,45640084,8
241,Kawhi Leonard,Los Angeles Clippers,F,6-7,225.0,San Diego State,45640084,8