# DataFrame I

In [1]:
import pandas as pd

In [26]:
nba = pd.read_csv("nba.csv")
nba.head(n=2)
nba.tail(n=2)
nba.index
nba.values  # np.ndarray
nba.shape
nba.dtypes  # pd.Series
nba.columns
nba.axes
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    object
 3   Height    585 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    488 non-null    float64
dtypes: float64(2), object(5)
memory usage: 32.5+ KB

In [18]:
revenue = pd.read_csv("revenue.csv", index_col="Date")
revenue.sum(axis="index")
revenue.sum(axis="columns")
revenue.sum().sum()

np.int64(16250)

In [24]:
nba = pd.read_csv("nba.csv")
nba.Team  # Case sensitive
nba.Salary
nba.Name
# nba.name
type(nba.Name)
nba["Team"]
nba["Salary"]

# names = nba["Name"]
# names.iloc[0] = "Whatever"
# names.head()
# nba.head()

names = nba["Name"].copy()
names.iloc[0] = "Whatever"
names.head()
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [8]:
nba = pd.read_csv("nba.csv")
nba[["Name", "Team"]]
nba[["Team", "Name"]]
nba[["Salary", "Name", "Team"]]
columns_to_select = ["Position", "Name", "Team"]
nba[columns_to_select]

    Position               Name                Team
0          F         Saddiq Bey       Atlanta Hawks
1          G  Bogdan Bogdanovic       Atlanta Hawks
2          G        Kobe Bufkin       Atlanta Hawks
3          C       Clint Capela       Atlanta Hawks
4        F-C     Bruno Fernando       Atlanta Hawks
..       ...                ...                 ...
587        G       Ryan Rollins  Washington Wizards
588        G      Landry Shamet  Washington Wizards
589        F   Tristan Vukcevic  Washington Wizards
590        G       Delon Wright  Washington Wizards
591      NaN                NaN                 NaN

[592 rows x 3 columns]

In [18]:
nba = pd.read_csv("nba.csv")
# nba["Sport"] = "Basketball"
nba.insert(loc=3, column="Sport", value="Basketball")
nba["Salary Doubled"] = nba["Salary"].mul(2)
nba["New Salary"] = nba["Salary"].sub(5000000)

nba

,Name,Team,Position,Sport,Height,Weight,College,Salary,Salary Doubled,New Salary
0,Saddiq Bey,Atlanta Hawks,F,Basketball,6-7,215.0,Villanova,4556983.0,9113966.0,-443017.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,Basketball,6-5,225.0,Fenerbahce,18700000.0,37400000.0,13700000.0
2,Kobe Bufkin,Atlanta Hawks,G,Basketball,6-5,195.0,Michigan,4094244.0,8188488.0,-905756.0
3,Clint Capela,Atlanta Hawks,C,Basketball,6-10,256.0,Elan Chalon,20616000.0,41232000.0,15616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,Basketball,6-10,240.0,Maryland,2581522.0,5163044.0,-2418478.0
...,...,...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,Basketball,6-3,180.0,Toledo,1719864.0,3439728.0,-3280136.0
588,Landry Shamet,Washington Wizards,G,Basketball,6-4,190.0,Wichita State,10250000.0,20500000.0,5250000.0
589,Tristan Vukcevic,Washington Wizards,F,Basketball,6-10,220.0,Real Madrid,NaN,NaN,NaN
590,Delon Wright,Washington Wizards,G,Basketball,6-5,185.0,Utah,8195122.0,16390244.0,3195122.0
591,NaN,NaN,NaN,Basketball,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
nba = pd.read_csv("nba.csv")
nba["Team"].value_counts(dropna=False)
nba["Position"].value_counts(normalize=True) * 100
nba["Salary"].value_counts()

Salary
559782.0      59
1119563.0     27
3196448.0     13
2019706.0      9
1719864.0      8
              ..
2966040.0      1
10900635.0     1
4570080.0      1
7921300.0      1
8195122.0      1
Name: count, Length: 298, dtype: int64

In [15]:
nba = pd.read_csv("nba.csv")
nba.dropna()
nba.dropna(how="all")
nba.dropna(subset=["College"])
nba.dropna(subset=["College", "Salary"])

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
585,Eugene Omoruyi,Washington Wizards,F,6-6,235.0,Oregon,559782.0
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0