# Merging dataframes

In [1]:
import pandas as pd

In [2]:
foods = pd.read_csv("restaurant_foods.csv")
customers = pd.read_csv("restaurant_customers.csv")
week1 = pd.read_csv("restaurant_week_1_sales.csv")
week2 = pd.read_csv("restaurant_week_2_sales.csv")

week1.head()
week2.head()
len(week1)
len(week2)
pd.concat([week1, week2])
pd.concat([week1, week2], ignore_index=True)
pd.concat([week1, week2], keys=["Week 1", "Week 2"]).sort_index()

            Customer ID  Food ID
Week 1 0            537        9
       1             97        4
       2            658        1
       3            202        2
       4            155        9
...                 ...      ...
Week 2 245          783       10
       246          556       10
       247          547        9
       248          252        9
       249          249        6

[500 rows x 2 columns]

In [10]:
df1 = pd.DataFrame([1, 2, 3], columns=["A"])
df2 = pd.DataFrame([4, 5, 6], columns=["B"])

pd.concat([df1, df2])
pd.concat([df1, df2], axis="columns")
pd.concat([df1, df2], axis=1)

   A  B
0  1  4
1  2  5
2  3  6

In [7]:
foods = pd.read_csv("restaurant_foods.csv")
customers = pd.read_csv("restaurant_customers.csv")
week1 = pd.read_csv("restaurant_week_1_sales.csv")
week2 = pd.read_csv("restaurant_week_2_sales.csv")

week1.head()
foods.head()
week1.merge(foods, how="left", on="Food ID")

     Customer ID  Food ID   Food Item  Price
0            537        9       Donut   0.99
1             97        4  Quesadilla   4.25
2            658        1       Sushi   3.99
3            202        2     Burrito   9.99
4            155        9       Donut   0.99
..           ...      ...         ...    ...
245          413        9       Donut   0.99
246          926        6       Pasta  13.99
247          134        3        Taco   2.99
248          396        6       Pasta  13.99
249          535       10       Drink   1.75

[250 rows x 4 columns]

In [15]:
foods = pd.read_csv("restaurant_foods.csv")
customers = pd.read_csv("restaurant_customers.csv")
week1 = pd.read_csv("restaurant_week_1_sales.csv")
week2 = pd.read_csv("restaurant_week_2_sales.csv")

week2.head()
customers.head()
week2.merge(customers, how="left", left_on="Customer ID", right_on="ID")
week2.merge(customers, how="left", left_on="Customer ID", right_on="ID").drop("ID", axis="columns")

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation
0,688,10,Carl,Williamson,Male,Thoughtmix,Graphic Designer
1,813,7,Johnny,Walker,Male,Kayveo,Developer II
2,495,10,Deborah,Little,Female,Babbleblab,VP Accounting
3,189,5,Roger,Gordon,Male,Skilith,Operator
4,267,3,Matthew,Wood,Male,Agimba,Product Engineer
...,...,...,...,...,...,...,...
245,783,10,Phyllis,Meyer,Female,Voolia,Information Systems Manager
246,556,10,Samuel,Bailey,Male,Oyoloo,Nurse
247,547,9,Tina,Watkins,Female,Thoughtstorm,Accountant II
248,252,9,Douglas,Powell,Male,Jetwire,Geologist IV
249,249,6,Anthony,Carpenter,Male,Shuffletag,Health Coach I

In [11]:
foods = pd.read_csv("restaurant_foods.csv")
customers = pd.read_csv("restaurant_customers.csv")
week1 = pd.read_csv("restaurant_week_1_sales.csv")
week2 = pd.read_csv("restaurant_week_2_sales.csv")

week1.merge(week2, how="inner", on="Customer ID", suffixes=[" - Week 1", " - Week 2"])

    Customer ID  Food ID - Week 1  Food ID - Week 2
0           537                 9                 5
1           155                 9                 3
2           503                 5                 8
3           503                 5                 9
4           155                 1                 3
..          ...               ...               ...
57          945                 5                 4
58          343                 3                 5
59          343                 3                 2
60          343                 3                 7
61          621                 9                 6

[62 rows x 3 columns]

In [9]:
week1[week1["Customer ID"] == 155]

    Customer ID  Food ID
4           155        9
17          155        1

In [10]:
week2[week2["Customer ID"] == 155]

     Customer ID  Food ID
208          155        3

In [14]:
foods = pd.read_csv("restaurant_foods.csv")
customers = pd.read_csv("restaurant_customers.csv")
week1 = pd.read_csv("restaurant_week_1_sales.csv")
week2 = pd.read_csv("restaurant_week_2_sales.csv")

week1.merge(week2, how="inner", on=["Customer ID", "Food ID"])

   Customer ID  Food ID
0          304        3
1          540        3
2          937       10
3          233        3
4           21        4
5          922        1
6           21        4
7          578        5
8          578        5

In [17]:
condition1 = week1["Customer ID"] == 21
condition2 = week1["Food ID"] == 4
week1[condition1 & condition2]

     Customer ID  Food ID
101           21        4
212           21        4

In [18]:
condition1 = week2["Customer ID"] == 21
condition2 = week2["Food ID"] == 4
week2[condition1 & condition2]

    Customer ID  Food ID
30           21        4

In [7]:
foods = pd.read_csv("restaurant_foods.csv")
customers = pd.read_csv("restaurant_customers.csv")
week1 = pd.read_csv("restaurant_week_1_sales.csv")
week2 = pd.read_csv("restaurant_week_2_sales.csv")

week1.merge(
    week2,
    how="outer",
    on="Customer ID",
    suffixes=[" - Week 1", " - Week 2"]
)
merged = week1.merge(
    week2,
    how="outer",
    on="Customer ID",
    suffixes=[" - Week 1", " - Week 2"],
    indicator=True
)

merged["_merge"].value_counts()
merged[merged["_merge"].isin(["left_only", "right_only"])]

     Customer ID  Food ID - Week 1  Food ID - Week 2      _merge
0              3               2.0               NaN   left_only
1              8               NaN               6.0  right_only
2             10               2.0               NaN   left_only
3             13               NaN               2.0  right_only
4             20               1.0               NaN   left_only
..           ...               ...               ...         ...
449          985               5.0               NaN   left_only
450          991               2.0               NaN   left_only
451          994               NaN               2.0  right_only
452          996               NaN              10.0  right_only
453         1000               2.0               NaN   left_only

[392 rows x 4 columns]

In [12]:
foods = pd.read_csv("restaurant_foods.csv", index_col="Food ID")
customers = pd.read_csv("restaurant_customers.csv", index_col="ID")
week1 = pd.read_csv("restaurant_week_1_sales.csv")
week2 = pd.read_csv("restaurant_week_2_sales.csv")

customers
week1.merge(
    customers, how="left", left_on="Customer ID", right_index=True
).merge(
    foods, how="left", left_on="Food ID", right_index=True
)

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation,Food Item,Price
0,537,9,Cheryl,Carroll,Female,Zoombeat,Registered Nurse,Donut,0.99
1,97,4,Amanda,Watkins,Female,Ozu,Account Coordinator,Quesadilla,4.25
2,658,1,Patrick,Webb,Male,Browsebug,Community Outreach Specialist,Sushi,3.99
3,202,2,Louis,Campbell,Male,Rhynoodle,Account Representative III,Burrito,9.99
4,155,9,Carolyn,Diaz,Female,Gigazoom,Database Administrator III,Donut,0.99
...,...,...,...,...,...,...,...,...,...
245,413,9,Diane,Bailey,Female,Wikibox,Technical Writer,Donut,0.99
246,926,6,Anne,Wagner,Female,Skyba,Legal Assistant,Pasta,13.99
247,134,3,Diana,Hall,Female,Quinu,Financial Advisor,Taco,2.99
248,396,6,Juan,Romero,Male,Zoonder,Analyst Programmer,Pasta,13.99
249,535,10,Nancy,Cox,Female,Trudeo,Research Associate,Drink,1.75

In [16]:
foods = pd.read_csv("restaurant_foods.csv")
customers = pd.read_csv("restaurant_customers.csv")
week1 = pd.read_csv("restaurant_week_1_sales.csv")
week2 = pd.read_csv("restaurant_week_2_sales.csv")
times = pd.read_csv("restaurant_week_1_times.csv")
week1.merge(times, how="left", left_index=True, right_index=True)
week1.join(times)

     Customer ID  Food ID Time of Day
0            537        9    14:54:59
1             97        4    20:55:17
2            658        1    01:16:22
3            202        2    16:17:26
4            155        9    19:26:11
..           ...      ...         ...
245          413        9    04:44:14
246          926        6    07:46:21
247          134        3    20:45:08
248          396        6    01:09:06
249          535       10    18:18:50

[250 rows x 3 columns]